# Generated by Django 4.2.27 on 2026-01-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'このメールアドレスは既に使用されています。'}, max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
